name: Deploy to Docker Hub
on:
  workflow_dispatch:  
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repository
        uses: actions/checkout@v4
      - name: Test go code
        id: test
        run: echo "Change to test go code"
      - name: Notify on failure
        if: steps.test.outputs.failure
        run: echo "Change to Notify that test failed"
  
  sast:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    steps:
      - name: Get Repository
        uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
            languages: "go"
      - name: Build CodeQL
        uses: github/codeql-action/autobuild@v3
      - name: Run CodeQL
        uses: github/codeql-action/analyze@v3
      - name: Export Results
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: reports

  lint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "linter"

  push_to_registry:
    environment: Dockerhub
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    needs:
      - test
      - sast
    steps:
      - name: Get Repository
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: kanelao/portfolio-backend
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
